// const OrderActionType = {
// 	DATA_REQUEST: 'DATA_REQUEST',
// 	GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS',
// 	GET_ORDER_ERROR: 'GET_ORDER_ERROR',
// 	CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
// 	CREATE_ORDER_ERROR: 'CREATE_ORDER_ERROR',
// 	CREATE_TRANSACTION_SUCCESS: 'CREATE_TRANSACTION_SUCCESS',
// 	CREATE_TRANSACTION_ERROR: 'CREATE_TRANSACTION_ERROR',
// 	GET_TRANSACTION_SUCCESS: 'GET_TRANSACTION_SUCCESS',
// 	GET_TRANSACTION_ERROR: 'GET_TRANSACTION_ERROR',
// };

// export default OrderActionType