const PersonalActionType = {
    'SIGN_OUT_SUCCESS': 'SIGN_OUT_SUCCESS',
    'SIGN_UP_SUCCESS' : 'SIGN_UP_SUCCESS',
    'SIGN_UP_ERROR': 'SIGN_UP_ERROR',
    'SIGN_IN_SUCCESS': 'SIGN_IN_SUCCESS',
    'SIGN_IN_ERROR': 'SIGN_IN_ERROR',
    'SEND_SMS_SUCCESS': 'SEND_SMS_SUCCESS',
    'SEND_SMS_ERROR': 'SEND_SMS_ERROR',
    'VERIFY_NUMBRER_SUCCESS'  : 'VERIFY_NUMBRER_SUCCESS',
    'VERIFY_NUMBRER_ERROR'  : 'VERIFY_NUMBRER_ERROR',
    'DATA_REQUEST': 'DATA_REQUEST'
}

export default PersonalActionType;
