const ProductActionType = {
	DATA_REQUEST: 'DATA_REQUEST',
	CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
	CREATE_PRODUCT_ERROR: 'CREATE_PRODUCT_ERROR',
	GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
	GET_PRODUCT_ERROR: 'GET_PRODUCT_ERROR',
};

export default ProductActionType;
