export const ADD_TO_CART = "ADD_TO_CART"
export const UPDATE_CART = "UPDATE_CART"
export const SET_CHECKOUT = "SET_CHECKOUT"
export const SET_CARTUI = "SET_CARTUI"
export const SET_CHECKOUT_FORM = "SET_CHECKOUT_FORM"
export const SET_SEARCH = "SET_SEARCH"