// const UserActionType = {
// 	SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
// 	SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
// 	SIGN_UP_ERROR: 'SIGN_UP_ERROR',
// 	SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
// 	SIGN_IN_ERROR: 'SIGN_IN_ERROR',
// 	SEND_SMS_SUCCESS: 'SEND_SMS_SUCCESS',
// 	SEND_SMS_ERROR: 'SEND_SMS_ERROR',
// 	VERIFY_NUMBRER_SUCCESS: 'VERIFY_NUMBRER_SUCCESS',
// 	VERIFY_NUMBRER_ERROR: 'VERIFY_NUMBRER_ERROR',
// 	DATA_REQUEST: 'DATA_REQUEST',
// 	GET_USER_DETAIL: 'GET_USER_DETAIL',
// 	GET_USER_DETAIL_SUCCESS: 'GET_USER_DETAIL_SUCCESS',
// 	GET_USER_DETAIL_ERROR: 'GET_USER_DETAIL_ERROR',
// 	CREATE_CUSTOMER_SUCCESS: 'CREATE_CUSTOMER_SUCCESS',
// 	CREATE_CUSTOMER_ERROR: 'CREATE_CUSTOMER_ERROR',
// 	GET_CUSTOMER_SUCCESS: 'GET_CUSTOMER_SUCCESS',
// 	GET_CUSTOMER_ERROR: 'GET_CUSTOMER_ERROR',
// 	CREDIT_USER_SUCCESS: 'CREDIT_USER_SUCCESS',
// 	CREDIT_USER_ERROR: 'CREDIT_USER_ERROR',
// 	UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',
// 	UPDATE_PASSWORD_ERROR: 'UPDATE_PASSWORD_ERROR',
// 	UPLOAD_IMAGE_SUCCESS: 'UPLOAD_IMAGE_SUCCESS',
// 	UPLOAD_IMAGE_ERROR: 'UPLOAD_IMAGE_ERROR',
// 	ADD_TEAM_SUCCESS: 'ADD_TEAM_SUCCESS',
// 	ADD_TEAM_ERROR: 'ADD_TEAM_ERROR',
// 	GET_TEAM_SUCCESS: 'GET_TEAM_SUCCESS',
// 	GET_TEAM_ERROR: 'GET_TEAM_ERROR',
// 	GET_CUSTOMER_SUCCESS: 'GET_CUSTOMER_SUCCESS',
// 	GET_CUSTOMER_ERROR: 'GET_CUSTOMER_ERROR',
// 	UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
// 	UPDATE_PROFILE_ERROR: 'UPDATE_PROFILE_ERROR',
// 	SEND_AUTH_CODE_SUCCESS: 'SEND_AUTH_CODE_SUCCESS',
// 	SEND_AUTH_CODE_ERROR: 'SEND_AUTH_CODE_ERROR',
// 	CREATE_STORELINK_SUCCESS: 'CREATE_STORELINK_SUCCESS',
// 	CREATE_STORELINK_ERROR: 'CREATE_STORELINK_ERROR',
// };

// export default UserActionType;

export const GET_USER_DETAIL = "GET_USER_DETAIL";
export const FETCH_USER_DETAIL_WITH_ID = "FETCH_USER_DETAIL_WITH_ID";
export const FETCH_USER_DETAIL_WITH_ID_SUCCESS =
  "FETCH_USER_DETAIL_WITH_ID_SUCCESS";
export const FETCH_USER_DETAIL_WITH_ID_ERROR =
  "FETCH_USER_DETAIL_WITH_ID_ERROR";
export const GET_BUSINESS_USER_DETAIL = "GET_BUSINESS_USER_DETAIL";
export const FETCH_BUSINESS_USER_DETAIL_WITH_ID =
  "FETCH_BUSINESS_USER_DETAIL_WITH_ID";
export const FETCH_BUSINESS_USER_DETAIL_WITH_ID_SUCCESS =
  "FETCH_BUSINESS_USER_DETAIL_WITH_ID_SUCCESS";
export const FETCH_BUSINESS_USER_DETAIL_WITH_ID_ERROR =
  "FETCH_BUSINESS_USER_DETAIL_WITH_ID_ERROR";
export const CREATE_ORDER_START = "CREATE_ORDER_START";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR";
export const GET_ORDER_START = "GET_ORDER_START";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_ERROR = "GET_ORDER_ERROR";
export const GET_ORDER_PAGINATION = "GET_ORDER_PAGINATION";
export const GET_ORDER_PAGINATION_ERROR = "GET_ORDER_PAGINATION_ERROR";
export const GET_PAYMENT_START = "GET_PAYMENT_START";
export const GET_PAYMENT_SUCCESS = "GET_PAYMENT_SUCCESS";
export const GET_PAYMENT_ERROR = "GET_PAYMENT_ERROR";
export const GET_CUSTOMERS_START = "GET_CUSTOMERS_START";
export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS";
export const GET_CUSTOMERS_ERROR = "GET_CUSTOMERS_ERROR";
export const GET_PRODUCTS_START = "GET_PRODUCTS_START";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";
