const UserActionType = {
	SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
	SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
	SIGN_UP_ERROR: 'SIGN_UP_ERROR',
	SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
	SIGN_IN_ERROR: 'SIGN_IN_ERROR',
	SEND_SMS_SUCCESS: 'SEND_SMS_SUCCESS',
	SEND_SMS_ERROR: 'SEND_SMS_ERROR',
	VERIFY_NUMBRER_SUCCESS: 'VERIFY_NUMBRER_SUCCESS',
	VERIFY_NUMBRER_ERROR: 'VERIFY_NUMBRER_ERROR',
	DATA_REQUEST: 'DATA_REQUEST',
	GET_USER_DETAIL_SUCCESS: 'GET_USER_DETAIL_SUCCESS',
	GET_USER_DETAIL_ERROR: 'GET_USER_DETAIL_ERROR',
	CREDIT_USER_SUCCESS: 'CREDIT_USER_SUCCESS',
	CREDIT_USER_ERROR: 'CREDIT_USER_ERROR',
	
};

export default UserActionType;
