const UserActionType = {
    'SIGN_OUT_SUCCESS': 'SIGN_OUT_SUCCESS',
    'SIGN_UP_SUCCESS' : 'SIGN_UP_SUCCESS',
    'SIGN_UP_ERROR': 'SIGN_UP_ERROR',
    'SIGN_IN_SUCCESS': 'SIGN_IN_SUCCESS',
    'SIGN_IN_ERROR': 'SIGN_IN_ERROR',
    'VERIFY_NUMBRER_SUCCESS'  : 'VERIFY_NUMBRER_SUCCESS',
    'VERIFY_NUMBRER_ERROR'  : 'VERIFY_NUMBRER_ERROR',
}

export default UserActionType
