export const GET_USER_DETAIL = "GET_USER_DETAIL";
export const FETCH_USER_DETAIL_WITH_ID = "FETCH_USER_DETAIL_WITH_ID";
export const FETCH_USER_DETAIL_WITH_ID_SUCCESS =
  "FETCH_USER_DETAIL_WITH_ID_SUCCESS";
export const FETCH_USER_DETAIL_WITH_ID_ERROR =
  "FETCH_USER_DETAIL_WITH_ID_ERROR";
export const GET_BUSINESS_USER_DETAIL = "GET_BUSINESS_USER_DETAIL";
export const FETCH_BUSINESS_USER_DETAIL_WITH_ID =
  "FETCH_BUSINESS_USER_DETAIL_WITH_ID";
export const FETCH_BUSINESS_USER_DETAIL_WITH_ID_SUCCESS =
  "FETCH_BUSINESS_USER_DETAIL_WITH_ID_SUCCESS";
export const FETCH_BUSINESS_USER_DETAIL_WITH_ID_ERROR =
  "FETCH_BUSINESS_USER_DETAIL_WITH_ID_ERROR";
export const CREATE_ORDER_START = "CREATE_ORDER_START";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR";
export const GET_ORDER_START = "GET_ORDER_START";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_ERROR = "GET_ORDER_ERROR";
export const GET_ORDER_PAGINATION = "GET_ORDER_PAGINATION";
export const GET_ORDER_PAGINATION_ERROR = "GET_ORDER_PAGINATION_ERROR";
export const GET_PAYMENT_START = "GET_PAYMENT_START";
export const GET_PAYMENT_SUCCESS = "GET_PAYMENT_SUCCESS";
export const GET_PAYMENT_ERROR = "GET_PAYMENT_ERROR";
export const GET_CUSTOMERS_START = "GET_CUSTOMERS_START";
export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS";
export const GET_CUSTOMERS_ERROR = "GET_CUSTOMERS_ERROR";
export const GET_PRODUCTS_START = "GET_PRODUCTS_START";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";
export const GET_STEP_ONE_DETAIL = "GET_STEP_ONE_DETAIL";
export const GET_STEP_TWO_DETAIL = "GET_STEP_TWO_DETAIL";
export const CREATE_STORE_LINK_START = "CREATE_STORE_LINK_START";
export const CREATE_STORE_LINK_SUCCESS = "CREATE_STORE_LINK_SUCCESS";
export const CREATE_STORE_LINK_ERROR = "CREATE_STORE_LINK_ERROR";
export const CREATE_PAYMENT_START = "CREATE_PAYMENT_START";
export const CREATE_PAYMENT_SUCCESS = "CREATE_PAYMENT_SUCCESS";
export const CREATE_PAYMENT_ERROR = "CREATE_PAYMENT_ERROR";
export const SAVE_TRANSACTION_DETAIL = "SAVE_TRANSACTION_DETAIL";
export const SET_MODAL = "SET_MODAL";
export const GET_BUSINESS_STAT_SUCCESS = "GET_BUSINESS_STAT_SUCCESS";
export const GET_BUSINESS_STAT_ERROR = "GET_BUSINESS_STAT_ERROR";
export const GET_BUSINESS_STAT_START = "GET_BUSINESS_STAT_START";
