// "@material-ui/core": "^4.12.4",
//     "@mui/material": "^5.10.0",
//     "@testing-library/jest-dom": "^5.16.1",
//     "@testing-library/react": "^12.1.2",
//     "@testing-library/user-event": "^13.5.0",
//"react-mono-js": "^1.1.2",
//"react-paystack": "^3.0.5",
//"react-qr-code": "^2.0.7",
//"react-qr-reader": "^2.2.0",
